sudo: required
dist: trusty

language: ruby
rvm:
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - sudo cat /etc/apt/sources.list
  - sudo ls -laR /etc/apt/sources.list.d
  - sudo cat /etc/apt/sources.list.d/*
  - sudo apt-get update
  - sudo apt-get install --yes mono-devel
  - chmod +x bin/TestServer/TestServer.exe
  - gem update bundler  # Travis bundler versions are quite out of date and can cause install errors - see: https://github.com/rubygems/rubygems/issues/1419

script:
  - bundle exec rspec --color --format documentation spec

