sudo: required
dist: trusty

addons:
  apt:
    packages:
      - mono-devel
      - openssl

language: ruby
rvm:
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - chmod +x bin/TestServer/TestServer.exe
  - sudo ldconfig

script:
  - bundle exec rspec --color --format documentation spec

